
source('annualGenerate.R')

annualplotTab <- tabItem(
  tabName='annualplot',
  fluidRow(
    box(width=4,
      h2('Annual Activity Analysis'),
      'The annual activity graph is a specific bar chart comparing animal frequency by month. This graph is useful for seeing how often an animal is observed by the camera traps at different times of the year.', br(), br(),
      'The X-axis consists of the months of the year, while the Y-axis represents the frequency of photos taken of a given species.', br(), br(),
      'You can use the filters to narrow down what photos you are interested in. You can also select multiple species to compare. The data for each species will be represented by a different color.', br(),
      h2('Data Filters'),
      multiInput(inputId='species_annual',
                 label='Select Species (1-5 species):',
                 choices=species_list,
                 selected=c('aardvark', 'aardwolf', 'baboon')),
      #selectInput(inputId= 'year_annual',
      #            label='Choose Year:',
      #            choices=year_list,
      #            selected=min(year_list)
      #            ),
      selectInput(inputId = "y_annual", 
                  label = "y-axis", 
                  choices = c("Count", "Frequency")),
      switchInput(inputId='advanced_options_selected_annual',
                  label='Show Advanced options',
                  value=FALSE),
      conditionalPanel(condition='input.advanced_options_selected_annual == true',
                       checkboxGroupInput(inputId = "standing_annual",
                                          label = "Standing",
                                          choices = standing_list,
                                          selected = c("Not standing", "Standing")),
                       checkboxGroupInput(inputId = "resting_annual",
                                          label = "Resting",
                                          choices = resting_list,
                                          selected = c("Not resting", "Resting")),
                       checkboxGroupInput(inputId = "moving_annual",
                                          label = "Moving",
                                          choices = moving_list,
                                          selected = c("Not moving", "Moving")),
                       checkboxGroupInput(inputId = "eating_annual",
                                          label = "Eating",
                                          choices = eating_list,
                                          selected = c("Not eating", "Eating")),
                       checkboxGroupInput(inputId = "interacting_annual",
                                          label = "Interacting",
                                          choices = interacting_list,
                                          selected = c("Not interacting", "Interacting")),
                       checkboxGroupInput(inputId = "babies_annual",
                                          label = "Babies",
                                          choices = babies_list,
                                          selected = c("No babies", "Babies")),
                       checkboxGroupInput(inputId ="habitat_annual",
                                          label = "Habitat (select any or all)",
                                          choices = habitat_list,
                                          selected = c("Dense Woodland",
                                                       "Grassland w/Trees",
                                                       "Open Grassland",
                                                       "Open Woodland/Shrubs")),
                       dateRangeInput(inputId ="date_annual",
                                      label = "Select date range",
                                      start  = startDate,
                                      end    = endDate,
                                      min    = startDate,
                                      max    = endDate,
                                      format = "mm/dd/yy",
                                      separator = " - ")
                       )
    ),
    box(width=8,
      h2('Output:'),
      plotOutput('annualplotRender'),
      downloadButton('annualDownload', 'Download')
    )
  )
)