
source('barGenerate.R')

barTab <- tabItem(
  tabName = 'barplot',
  fluidRow(
    box(width=4,
      h2('Bar Charts - animal frequency beteween categories'),
      'The bar chart graph is useful for comparing animal frequency between categories of a categorical or binary variable.', br(), br(),
      'The X-axis consists of categories for the given variable. The Y-axis is the frequency of photos taken of a given species in each category. The Y-axis can be changed to absolute frequency (# of photos) or relative frequency (fraction of photos in each category).',  br(), br(),
      'You can use the filters to narrow down what photos you are interested in. You can also select multiple species to compare. The data for each species will be represented by a different color.', br(),
      h2('Data Filters'),
      selectInput(inputId = "x_bar", 
                  label = "x-axis", 
                  choices = categorical_vars,
                  selected = "Babies"),
      selectInput(inputId = "y_bar", 
                  label = "y-axis", 
                  choices = c("Count", "Frequency"),
                  selected = "Count"),
      multiInput(inputId = "species_bar", 
                 label = "Species (select up to five)", 
                 choices = species_list,
                 selected = c("aardvark")),
      switchInput(inputId='advanced_options_selected_bar',
                  label='Show Advanced options',
                  value=FALSE),
      conditionalPanel(condition='input.advanced_options_selected_bar == true',
                       checkboxGroupInput(inputId = "standing_bar",
                                          label = "Standing",
                                          choices = standing_list,
                                          selected = c("Not standing", "Standing")),
                       checkboxGroupInput(inputId = "resting_bar",
                                          label = "Resting",
                                          choices = resting_list,
                                          selected = c("Not resting", "Resting")),
                       checkboxGroupInput(inputId = "moving_bar",
                                          label = "Moving",
                                          choices = moving_list,
                                          selected = c("Not moving", "Moving")),
                       checkboxGroupInput(inputId = "eating_bar",
                                          label = "Eating",
                                          choices = eating_list,
                                          selected = c("Not eating", "Eating")),
                       checkboxGroupInput(inputId = "interacting_bar",
                                          label = "Interacting",
                                          choices = interacting_list,
                                          selected = c("Not interacting", "Interacting")),
                       checkboxGroupInput(inputId = "babies_bar",
                                          label = "Babies",
                                          choices = babies_list,
                                          selected = c("No babies", "Babies")),
                       checkboxGroupInput(inputId ="habitat_bar",
                                          label = "Habitat (select any or all)",
                                          choices = habitat_list,
                                          selected = c("Dense Woodland",
                                                       "Grassland w/Trees",
                                                       "Open Grassland",
                                                       "Open Woodland/Shrubs")),
                       dateRangeInput(inputId ="date_bar",
                                      label = "Select date range",
                                      start  = startDate,
                                      end    = endDate,
                                      min    = startDate,
                                      max    = endDate,
                                      format = "mm/dd/yy",
                                      separator = " - "))
      
    ),
    box(width=8,
      h2('Output:'),
      plotOutput('barplotRender'),
      downloadButton('barDownload', 'Download')
    )
  )
)