
source('histoGenerate.R')

histoTab <- tabItem(
  tabName='histoplot',
  fluidRow(
    box(width=4,
      h2('Histograms - animal frequency between continuous variables'),
      'The histogram graph is useful for comparing animal frequency across the range of a continuous variable.', br(), br(),
      'The X-axis is the continuous variable divided into equally sized bins. The Y-axis is the frequency of photos taken of a given species within each bin. The Y-axis can be changed to absolute frequency (# of photos) or relative frequency (fraction of photos in each category).', br(), br(),
      'You can use the filters to narrow down what photos you are interested in. You can also select multiple species to compare. The data for each species will be represented by a different color.', br(),
      h2('Data Filters:'),
      selectInput(inputId = "x_histo", 
                  label = "x-axis", 
                  choices = continuous_vars_no_log,
                  selected = "Distance_to_River_m"),
      multiInput(inputId = "species_histo", 
                 label = "Species (select up to five)", 
                 choices = species_list,
                 selected = c("aardvark")),
      switchInput(inputId='advanced_options_selected_histo',
                  label='Show Advanced options',
                  value=FALSE),
      conditionalPanel(condition='input.advanced_options_selected_histo == true',
                       checkboxGroupInput(inputId = "standing_histo",
                                          label = "Standing",
                                          choices = standing_list,
                                          selected = c("Not standing", "Standing")),
                       checkboxGroupInput(inputId = "resting_histo",
                                          label = "Resting",
                                          choices = resting_list,
                                          selected = c("Not resting", "Resting")),
                       checkboxGroupInput(inputId = "moving_histo",
                                          label = "Moving",
                                          choices = moving_list,
                                          selected = c("Not moving", "Moving")),
                       checkboxGroupInput(inputId = "eating_histo",
                                          label = "Eating",
                                          choices = eating_list,
                                          selected = c("Not eating", "Eating")),
                       checkboxGroupInput(inputId = "interacting_histo",
                                          label = "Interacting",
                                          choices = interacting_list,
                                          selected = c("Not interacting", "Interacting")),
                       checkboxGroupInput(inputId = "babies_histo",
                                          label = "Babies",
                                          choices = babies_list,
                                          selected = c("No babies", "Babies")),
                       checkboxGroupInput(inputId ="habitat_histo",
                                          label = "Habitat (select any or all)",
                                          choices = habitat_list,
                                          selected = c("Dense Woodland",
                                                       "Grassland w/Trees",
                                                       "Open Grassland",
                                                       "Open Woodland/Shrubs")),
                       dateRangeInput(inputId ="date_histo",
                                      label = "Select date range",
                                      start  = startDate,
                                      end    = endDate,
                                      min    = startDate,
                                      max    = endDate,
                                      format = "mm/dd/yy",
                                      separator = " - "))
    ),
    box(width=8,
        h2('Output:'),
        plotOutput('histoplotRender'),
        downloadButton('histoDownload', 'Download')
    )
  )
)