
source('scatterGenerate.R')

# scatterplot tab
scatterplotTab <- tabItem(
  tabName = 'scatterplot',
  
  # Row for activity description and for data filters
  fluidRow(
    box(width=4,
      h2('Scatterplots and comparing continuous variables'),
      'Scatterplots are useful graphs for exploring the relationship between two continuous variables.', br(), br(),
      'In this scatterplot, each dot represents data from a single photo from a specific camera trap. The line (regression line) represents the “average” relationship between two variables, averaged across all the data points.', br(), br(),
      'You can use the filters to narrow down what photos you are interested in. You can also select multiple species to compare. The data for each species will be represented by a different color.', br(),
      h2('Data Filters:'),
      selectInput(inputId = "x_scatter", 
                  label = "x-axis", 
                  choices = continuous_vars,
                  selected = "Amount_of_Shade"),
      selectInput(inputId = "y_scatter", 
                  label = "y-axis", 
                  choices = continuous_vars,
                  selected = "Distance_to_Confluence_m"),
      multiInput(inputId = "species_scatter", 
                 label = "Species (select up to five)", 
                 choices = species_list,
                 selected = c("aardvark")),
      switchInput(inputId='advanced_options_selected_scatter',
                  label='Show Advanced options',
                  value=FALSE),
      
      conditionalPanel(condition='input.advanced_options_selected_scatter == true',
                       checkboxGroupInput(inputId = "standing_scatter",
                                          label = "Standing",
                                          choices = standing_list,
                                          selected = c("Not standing", "Standing")),
                       checkboxGroupInput(inputId = "resting_scatter",
                                          label = "Resting",
                                          choices = resting_list,
                                          selected = c("Not resting", "Resting")),
                       checkboxGroupInput(inputId = "moving_scatter",
                                          label = "Moving",
                                          choices = moving_list,
                                          selected = c("Not moving", "Moving")),
                       checkboxGroupInput(inputId = "eating_scatter",
                                          label = "Eating",
                                          choices = eating_list,
                                          selected = c("Not eating", "Eating")),
                       checkboxGroupInput(inputId = "interacting_scatter",
                                          label = "Interacting",
                                          choices = interacting_list,
                                          selected = c("Not interacting", "Interacting")),
                       checkboxGroupInput(inputId = "babies_scatter",
                                          label = "Babies",
                                          choices = babies_list,
                                          selected = c("No babies", "Babies")),
                       checkboxGroupInput(inputId ="habitat_scatter",
                                          label = "Habitat (select any or all)",
                                          choices = habitat_list,
                                          selected = c("Dense Woodland",
                                                       "Grassland w/Trees",
                                                       "Open Grassland",
                                                       "Open Woodland/Shrubs")),
                       dateRangeInput(inputId ="date_scatter",
                                      label = "Select date range",
                                      start  = startDate,
                                      end    = endDate,
                                      min    = startDate,
                                      max    = endDate,
                                      format = "mm/dd/yy",
                                      separator = " - "))
    ),
    box(width=8,
        h2('Output:'),
        plotOutput('scatterplotRender'),
        downloadButton('scatterDownload', 'Download')
    )
  )
)
