
source('spatialGenerate.R')

spatialplotTab <- tabItem(
  tabName='spatialplot',
  fluidRow(
    box(width=4,
        h2('Spatial Distribution Analysis'),
        'This map graph is useful for comparing animal frequency across both space and time, as well as, in relation to continuous environmental data.', br(), br(),
        'Data for each species is plotted as a series of points. Each point is a camera trap in the research site. The colors correspond to the frequency of photos taken of that species at that camera site. You can toggle between different base maps, as well as, compare the distribution of different environmental variables at each camera site.', br(), br(),
        'You can use the filters to narrow down what photos you are interested in. Click the advance option to select additional filters. You can also select multiple species to compare. The data for each species will be represented by a different color.', br(),
        h2('Data Filters:'),
        multiInput(inputId='species_spatial',
                   label='Select Species (1-5 species):',
                   choices=species_list,
                   selected=c('cheetah')),
        switchInput(inputId='advanced_options_selected_spatial',
                    label='Show Advanced options',
                    value=FALSE),
        conditionalPanel(condition='input.advanced_options_selected_spatial == true',
                         selectInput(inputId = "meta_spatial", 
                                     label = "Metadata variable", 
                                     choices = continuous_vars_no_log,
                                     selected = 'Greeness_Dry'),
                         checkboxGroupInput(inputId = "standing_spatial",
                                            label = "Standing",
                                            choices = standing_list,
                                            selected = c("Not standing", "Standing")),
                         checkboxGroupInput(inputId = "resting_spatial",
                                            label = "Resting",
                                            choices = resting_list,
                                            selected = c("Not resting", "Resting")),
                         checkboxGroupInput(inputId = "moving_spatial",
                                            label = "Moving",
                                            choices = moving_list,
                                            selected = c("Not moving", "Moving")),
                         checkboxGroupInput(inputId = "eating_spatial",
                                            label = "Eating",
                                            choices = eating_list,
                                            selected = c("Not eating", "Eating")),
                         checkboxGroupInput(inputId = "interacting_spatial",
                                            label = "Interacting",
                                            choices = interacting_list,
                                            selected = c("Not interacting", "Interacting")),
                         checkboxGroupInput(inputId = "babies_spatial",
                                            label = "Babies",
                                            choices = babies_list,
                                            selected = c("No babies", "Babies")),
                         checkboxGroupInput(inputId ="habitat_spatial",
                                            label = "Habitat (select any or all)",
                                            choices = habitat_list,
                                            selected = c("Dense Woodland",
                                                         "Grassland w/Trees",
                                                         "Open Grassland",
                                                         "Open Woodland/Shrubs")),
                         dateRangeInput(inputId ="date_spatial",
                                        label = "Select date range",
                                        start  = startDate,
                                        end    = endDate,
                                        min    = startDate,
                                        max    = endDate,
                                        format = "mm/dd/yy",
                                        separator = " - "))
    ),
    box(width=8,
        h2('Output'),
        mapviewOutput('spatialplotRender')
    )
  )
)